services:
    app:
        image: ghcr.io/govigilant/vigilant:latest
        build:
            context: .
        volumes:
            - type: bind
              source: ./.env
              target: /app/.env
            - ./storage:/app/storage
            - public:/app/public
        restart: always
        working_dir: /app
        networks:
            - vigilant
        healthcheck:
            test: curl --fail http://localhost:8000 || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8000:8000"

    horizon:
        image: ghcr.io/govigilant/vigilant:latest
        volumes:
            - type: bind
              source: ./.env
              target: /app/.env
              read_only: true
            - ./storage:/app/storage
            - public:/app/public
        restart: always
        working_dir: /app
        networks:
            - vigilant
        entrypoint: ["php", "artisan", "horizon"]
        healthcheck:
            test: ["CMD", "php", "artisan", "horizon:status"]
            interval: 30s
            timeout: 10s
            start_period: 10s
            retries: 3
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=vigilant
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - database:/var/lib/mysql
        networks:
            - vigilant
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 20s
            retries: 10

    redis:
        image: redis:7
        restart: always
        volumes:
            - redis:/data
        networks:
            - vigilant
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    lighthouse:
        image: ghcr.io/govigilant/lighthouse-server:latest
        restart: always
        deploy:
            resources:
                reservations:
                    memory: 2G
        networks:
            - vigilant

    outpost:
        image: ghcr.io/govigilant/vigilant-uptime-outpost:latest
        restart: always
        environment:
            - VIGILANT_URL=http://app:8000
            - OUTPOST_SECRET=outpost-secret
        depends_on:
            app:
                condition: service_healthy
        networks:
            - vigilant

networks:
    vigilant:

volumes:
    public:
    database:
    redis:
