<div>
    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
        {{ __('Your Healthcheck Token') }}
    </label>

    @if ($healthcheck->type->generatesOwnToken())
        <form wire:submit="save" class="space-y-3"
            x-data="{
                copied: false,
                copy() {
                    navigator.clipboard.writeText($refs.tokenInput.value).then(() => {
                        this.copied = true;
                        setTimeout(() => this.copied = false, 2000);
                    });
                }
            }">
            <div class="flex items-center gap-2">
                <input type="text" wire:model.defer="token" x-ref="tokenInput"
                    class="flex-1 px-3 py-2 bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-600 rounded-md font-mono text-sm text-gray-900 dark:text-gray-100"
                    autocomplete="off" />
                <button type="button" @click="copy()"
                    class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm font-medium transition-colors duration-200">
                    <span x-text="copied ? '{{ __('Copied!') }}' : '{{ __('Copy') }}'"></span>
                </button>
            </div>
            <p class="text-sm text-gray-600 dark:text-gray-400">
                {{ __('Enter the token generated by :platform and save it here to authenticate healthchecks.', ['platform' => $healthcheck->type->label()]) }}
            </p>
            <div class="flex justify-end">
                <button type="submit" wire:loading.attr="disabled"
                    class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md text-sm font-medium">
                    <span wire:loading.remove>{{ __('Save Token') }}</span>
                    <span wire:loading>{{ __('Saving...') }}</span>
                </button>
            </div>
        </form>
    @else
        <div class="space-y-2"
            x-data="{
                copied: false,
                copy() {
                    navigator.clipboard.writeText($refs.tokenInput.value).then(() => {
                        this.copied = true;
                        setTimeout(() => this.copied = false, 2000);
                    });
                }
            }">
            <div class="flex items-center gap-2">
                <input type="text" readonly value="{{ $healthcheck->token }}" x-ref="tokenInput"
                    class="flex-1 px-3 py-2 bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-md font-mono text-sm text-gray-900 dark:text-gray-100" />
                <button type="button" @click="copy()"
                    class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm font-medium transition-colors duration-200">
                    <span x-text="copied ? '{{ __('Copied!') }}' : '{{ __('Copy') }}'"></span>
                </button>
            </div>
            <p class="text-sm text-gray-600 dark:text-gray-400">
                {{ __('This token is generated by Vigilant. Copy it into your platform configuration to enable healthchecks.') }}
            </p>
        </div>
    @endif
</div>
