<?php

return [
    'queue' => 'crawler',

    'timeout' => env('CRAWLER_TIMEOUT', 5),
    'connect_timeout' => env('CRAWLER_CONNECT_TIMEOUT', 2),

    'crawls_per_minute' => (int) env('CRAWLER_CRAWLS_PER_MINUTE', 500),

    'platform_blacklists' => [
        'magento1' => [
            'label' => 'Magento 1',
            'patterns' => [
                '~^https?://[^/]+/index\.php/admin~i',
                '~^https?://[^/]+/admin~i',
                '~^https?://[^/]+/api/~i',
                '~^https?://[^/]+/cron\.php~i',
                '~^https?://[^/]+/index\.php/customer/account~i',
                '~^https?://[^/]+/customer/account/login~i',
                '~^https?://[^/]+/customer/account/create~i',
                '~^https?://[^/]+/customer/account/logout~i',
                '~^https?://[^/]+/checkout/~i',
                '~^https?://[^/]+/cart~i',
                '~^https?://[^/]+/wishlist/~i',
                '~^https?://[^/]+/review/product/~i',
                '~^https?://[^/]+/newsletter/subscriber/~i',
                '~^https?://[^/]+/contacts/index/post~i',
                '~^https?://[^/]+/catalogsearch/ajax/~i',
                '~^https?://[^/]+/sendfriend/~i',
                '~^https?://[^/]+/catalog/product_compare/~i',
                '~^https?://[^/]+/tag/~i',
                '~^https?://[^/]+/rating/~i',
                '~^https?://[^/]+/poll/~i',
                '~^https?://[^/]+/paypal/~i',
            ],
        ],
        'magento2' => [
            'label' => 'Magento 2',
            'patterns' => [
                '~^https?://[^/]+/admin~i',
                '~^https?://[^/]+/rest/~i',
                '~^https?://[^/]+/graphql~i',
                '~^https?://[^/]+/soap/~i',
                '~^https?://[^/]+/cron\.php~i',
                '~^https?://[^/]+/index\.php/customer/account~i',
                '~^https?://[^/]+/customer/account/login~i',
                '~^https?://[^/]+/customer/account/create~i',
                '~^https?://[^/]+/customer/account/logout~i',
                '~^https?://[^/]+/checkout/~i',
                '~^https?://[^/]+/onestepcheckout/~i',
                '~^https?://[^/]+/cart~i',
                '~^https?://[^/]+/wishlist/~i',
                '~^https?://[^/]+/review/product/~i',
                '~^https?://[^/]+/newsletter/subscriber/~i',
                '~^https?://[^/]+/contact/index/post~i',
                '~^https?://[^/]+/search/ajax/~i',
                '~^https?://[^/]+/catalogsearch/ajax/~i',
                '~^https?://[^/]+/page_cache/~i',
                '~^https?://[^/]+/static/version~i',
                '~^https?://[^/]+/media/tmp/~i',
                '~^https?://[^/]+/pub/media/tmp/~i',
                '~^https?://[^/]+/sendfriend/~i',
                '~^https?://[^/]+/catalog/product_compare/~i',
            ],
        ],
        'wordpress' => [
            'label' => 'WordPress',
            'patterns' => [
                '~^https?://[^/]+/wp-admin~i',
                '~^https?://[^/]+/wp-login\.php~i',
                '~^https?://[^/]+/wp-cron\.php~i',
                '~^https?://[^/]+/wp-json/~i',
                '~^https?://[^/]+/xmlrpc\.php~i',
                '~^https?://[^/]+/\?feed=~i',
                '~^https?://[^/]+/feed/~i',
                '~^https?://[^/]+/comments/feed/~i',
                '~[?&]replytocom=~i',
                '~[?&]preview=true~i',
                '~^https?://[^/]+/\?p=\d+&preview=true~i',
                '~^https?://[^/]+/wp-content/uploads/~i',
                '~^https?://[^/]+/\?add-to-cart=~i',
                '~^https?://[^/]+/cart/~i',
                '~^https?://[^/]+/checkout/~i',
                '~^https?://[^/]+/my-account/~i',
                '~^https?://[^/]+/\?wc-ajax=~i',
                '~^https?://[^/]+/wp-trackback\.php~i',
            ],
        ],
        'joomla' => [
            'label' => 'Joomla',
            'patterns' => [
                '~^https?://[^/]+/administrator/~i',
                '~^https?://[^/]+/index\.php\?option=com_users&task=user\.login~i',
                '~^https?://[^/]+/index\.php\?option=com_users&task=user\.logout~i',
                '~^https?://[^/]+/index\.php\?option=com_users&task=registration~i',
                '~^https?://[^/]+/index\.php\?option=com_contact&task=contact\.submit~i',
                '~[?&]format=feed~i',
                '~[?&]format=json~i',
                '~[?&]format=raw~i',
                '~[?&]tmpl=component~i',
                '~^https?://[^/]+/index\.php\?option=com_search~i',
                '~^https?://[^/]+/index\.php\?option=com_finder~i',
                '~^https?://[^/]+/index\.php\?option=com_ajax~i',
                '~^https?://[^/]+/cache/~i',
                '~^https?://[^/]+/tmp/~i',
                '~^https?://[^/]+/logs/~i',
                '~^https?://[^/]+/cli/~i',
            ],
        ],
        'drupal' => [
            'label' => 'Drupal',
            'patterns' => [
                '~^https?://[^/]+/admin/~i',
                '~^https?://[^/]+/user/login~i',
                '~^https?://[^/]+/user/logout~i',
                '~^https?://[^/]+/user/register~i',
                '~^https?://[^/]+/user/password~i',
                '~^https?://[^/]+/\?q=user/~i',
                '~^https?://[^/]+/\?q=admin/~i',
                '~^https?://[^/]+/jsonapi/~i',
                '~^https?://[^/]+/api/~i',
                '~^https?://[^/]+/batch\b~i',
                '~[?&]ajax_form=1~i',
                '~^https?://[^/]+/cron/~i',
                '~^https?://[^/]+/update\.php~i',
                '~^https?://[^/]+/install\.php~i',
                '~^https?://[^/]+/rebuild\.php~i',
                '~^https?://[^/]+/core/rebuild\.php~i',
                '~^https?://[^/]+/sites/default/files/~i',
            ],
        ],
    ],
];
