[supervisord]
nodaemon=true
logfile=/app/storage/logs/supervisord.log
logfile_maxbytes=10MB

[program:cron]
command=/usr/sbin/crond -f -l 8
stdout_logfile=/app/storage/logs/cron.log
stderr_logfile=/app/storage/logs/cron-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
autorestart=true

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/app/storage/logs/php-fpm.log
redirect_stderr=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/app/storage/logs/nginx.log
redirect_stderr=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
autorestart=true
