name: Dusk

on: [ 'push', 'pull_request' ]

jobs:
  dusk:
    name: Dusk
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vigilant_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Setup
        run: |
          composer install --prefer-dist --no-interaction
          npm install
          npm run build

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Wait for MySQL to initialize
        run: sleep 10

      - name: Run Dusk Tests
        run: php artisan dusk --stop-on-error --stop-on-failure

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: screenshots/
