name: Dusk

on: [ 'push', 'pull_request' ]

jobs:
  dusk:
    name: Dusk
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: vigilant_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Setup
        run: |
          composer install --prefer-dist --no-interaction
          npm install
          npm run build
          cp .env.dusk .env

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/
